# Generated by Django 3.2.6 on 2021-08-31 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='logos/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('Genero', models.CharField(max_length=200)),
                ('Plataforma', models.CharField(max_length=150)),
                ('dataLançamento', models.DateTimeField(default=datetime.datetime(2021, 8, 31, 12, 45, 54, 75112, tzinfo=utc))),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/')),
                ('Desenvolvedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.empresa')),
            ],
        ),
    ]
