# Generated by Django 3.2.6 on 2021-08-31 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dataLançamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 12, 49, 23, 408890, tzinfo=utc)),
        ),
    ]
