# Generated by Django 3.2.6 on 2021-09-01 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_game_datalançamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dataLançamento',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 13, 30, 41, 280377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='descricao',
            field=models.CharField(max_length=700),
        ),
    ]
